
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[override]]
  name = "github.com/opencontainers/image-spec"
  version = "=v1.0.0-rc4"

[[override]]
  name = "github.com/docker/go-connections"
  revision = "7da10c8c50cad14494ec818dcdfb6506265c0086"

[[override]]
  name = "github.com/containers/storage"
  revision = "ff48947baaf205756dd67a00ac688d694a778ef6"

[[override]]
  name = "github.com/containers/image"
  revision = "cb1908f14e99f5f26bf30d8786bbae71bbd4bd4a"
